#!/usr/bin/env bash
# 06_sound — MSX-DOS2 .COM build (z88dk + ubox + mplayer-z88dk REAL).
# Same pipeline as compile.sh; only ZCC subtype differs.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
BUILD_DIR="$SCRIPT_DIR/build_dos"
TARGET_BASE="06_sound"

ZCC="${ZCC:-/opt/z88dk/bin/zcc}"
RASM="${RASM:-$PROJECT_ROOT/Examples/ubox_example_z88dk/bin/rasm}"
UBOX_DIR="$PROJECT_ROOT/Library/MSX/ubox-msx-lib-z88dk"
UBOX_INC="$UBOX_DIR/include"
UBOX_LIB="$UBOX_DIR/lib"
MPLAYER_DIR="$PROJECT_ROOT/Library/MSX/mplayer-z88dk"
MPLAYER_INC="$MPLAYER_DIR/include"
MPLAYER_WRAPPERS="$MPLAYER_DIR/src/wrappers"
MPLAYER_BRIDGE_SRC="$MPLAYER_DIR/src/akm/akm_bridge.asm"

[[ -x "$ZCC"  ]] || { echo "Error: zcc not found at $ZCC"   >&2; exit 1; }
[[ -x "$RASM" ]] || { echo "Error: rasm not found"          >&2; exit 1; }
[[ -f "$UBOX_LIB/ubox.lib" ]] || { echo "ubox.lib missing — building..."; make -C "$UBOX_DIR"; }

mkdir -p "$BUILD_DIR"

echo "[rasm] src/akm.z80 → build_dos/akm.bin (ORG=\$C200)"
(cd "$SCRIPT_DIR/src" && "$RASM" akm.z80 \
    -ob "$BUILD_DIR/akm.bin" \
    -os "$BUILD_DIR/akm.sym" \
    -s -sl >/dev/null 2>&1) \
    || { echo "Error: rasm failed assembling src/akm.z80" >&2; exit 1; }
echo "  akm.bin: $(wc -c < "$BUILD_DIR/akm.bin") bytes"

cp -f "$MPLAYER_BRIDGE_SRC" "$BUILD_DIR/akm_bridge.asm"

extract_addr() {
    local label="$1"
    local hex_with_prefix
    hex_with_prefix="$(awk -v L="$label" '$1==L { print $2 }' "$BUILD_DIR/akm.sym")"
    if [[ -n "$hex_with_prefix" ]]; then
        echo "${hex_with_prefix/\#/\$}"
    fi
    return 0
}
SONG_ADDR="$(extract_addr SONGDISARKGENERATEEXTERNALLABEL)" || true
EFFECTS_ADDR="$(extract_addr EFFECTSDISARKGENERATEEXTERNALLABEL)" || true
[[ -n "$SONG_ADDR" ]] || { echo "Error: SONGDISARKGENERATEEXTERNALLABEL not in akm.sym" >&2; exit 1; }

PLY_INIT="$(extract_addr PLY_AKM_INIT)"
PLY_PLAY="$(extract_addr PLY_AKM_PLAY)"
PLY_STOP="$(extract_addr PLY_AKM_STOP)"
PLY_INITSFX="$(extract_addr PLY_AKM_INITSOUNDEFFECTS)"
PLY_ISSFXON="$(extract_addr PLY_AKM_ISSOUNDEFFECTON)"
PLY_PLAYSFX="$(extract_addr PLY_AKM_PLAYSOUNDEFFECT)"
PLY_STOPSFX="$(extract_addr PLY_AKM_STOPSOUNDEFFECTFROMCHANNEL)"
for sym in PLY_INIT PLY_PLAY PLY_STOP PLY_INITSFX PLY_ISSFXON PLY_PLAYSFX PLY_STOPSFX; do
    [[ -n "${!sym}" ]] || { echo "Error: $sym address missing in akm.sym" >&2; exit 1; }
done

{
    echo "; Auto-generated by compile_dos.sh"
    echo "    SECTION code_user"
    echo "    PUBLIC _SONG"
    echo "    DEFC _SONG = $SONG_ADDR"
    if [[ -n "$EFFECTS_ADDR" ]]; then
        echo "    PUBLIC _EFFECTS"
        echo "    DEFC _EFFECTS = $EFFECTS_ADDR"
    fi
    echo "    PUBLIC _PLY_AKM_INIT"
    echo "    DEFC _PLY_AKM_INIT = $PLY_INIT"
    echo "    PUBLIC _PLY_AKM_PLAY"
    echo "    DEFC _PLY_AKM_PLAY = $PLY_PLAY"
    echo "    PUBLIC _PLY_AKM_STOP"
    echo "    DEFC _PLY_AKM_STOP = $PLY_STOP"
    echo "    PUBLIC _PLY_AKM_INITSOUNDEFFECTS"
    echo "    DEFC _PLY_AKM_INITSOUNDEFFECTS = $PLY_INITSFX"
    echo "    PUBLIC _PLY_AKM_ISSOUNDEFFECTON"
    echo "    DEFC _PLY_AKM_ISSOUNDEFFECTON = $PLY_ISSFXON"
    echo "    PUBLIC _PLY_AKM_PLAYSOUNDEFFECT"
    echo "    DEFC _PLY_AKM_PLAYSOUNDEFFECT = $PLY_PLAYSFX"
    echo "    PUBLIC _PLY_AKM_STOPSOUNDEFFECTFROMCHANNEL"
    echo "    DEFC _PLY_AKM_STOPSOUNDEFFECTFROMCHANNEL = $PLY_STOPSFX"
} > "$BUILD_DIR/song_bindings.asm"
echo "  _SONG = $SONG_ADDR${EFFECTS_ADDR:+, _EFFECTS = $EFFECTS_ADDR}"
echo "  PLY_AKM_INIT=$PLY_INIT PLAY=$PLY_PLAY PLAYSFX=$PLY_PLAYSFX"

ZCCFLAGS="+msx -subtype=msxdos2 -compiler=sccz80 -SO2 -create-app"
ZCCFLAGS="$ZCCFLAGS -I$UBOX_INC -I$MPLAYER_INC -I$SCRIPT_DIR/src"
ZCCFLAGS="$ZCCFLAGS -L$UBOX_LIB -lubox"
ZCCFLAGS="$ZCCFLAGS -DMSXDOS"

WRAPPER_SRCS=(
    "$MPLAYER_WRAPPERS/mplayer_init.asm"
    "$MPLAYER_WRAPPERS/mplayer_init_effects.asm"
    "$MPLAYER_WRAPPERS/mplayer_is_sound_effect_on.asm"
    "$MPLAYER_WRAPPERS/mplayer_play.asm"
    "$MPLAYER_WRAPPERS/mplayer_play_effect.asm"
    "$MPLAYER_WRAPPERS/mplayer_play_effect_p.asm"
    "$MPLAYER_WRAPPERS/mplayer_stop.asm"
    "$MPLAYER_WRAPPERS/mplayer_stop_effect_channel.asm"
)

case "${1:-build}" in
    build|all)
        echo "[zcc DOS] main_dos.c + wrappers + akm_bridge → build_dos/$TARGET_BASE"
        (cd "$SCRIPT_DIR" && "$ZCC" $ZCCFLAGS -m \
            -o "$BUILD_DIR/$TARGET_BASE" \
            src/main_dos.c \
            "${WRAPPER_SRCS[@]}" \
            "$BUILD_DIR/akm_bridge.asm" \
            "$BUILD_DIR/song_bindings.asm")

        COM=""
        [[ -f "$BUILD_DIR/${TARGET_BASE}.COM" ]] && COM="$BUILD_DIR/${TARGET_BASE}.COM"
        [[ -z "$COM" && -f "$BUILD_DIR/$TARGET_BASE" ]] && COM="$BUILD_DIR/$TARGET_BASE"
        [[ -z "$COM" ]] && { echo "Error: COM not produced" >&2; exit 1; }
        echo "COM: $COM ($(wc -c < "$COM") bytes)"
        ;;
    clean) rm -rf "$BUILD_DIR"; echo "Cleaned: $BUILD_DIR" ;;
    *) echo "usage: $0 {build|clean|all}" >&2; exit 2 ;;
esac
