#!/usr/bin/env bash
# 06_sound — ROM cartridge build (z88dk + ubox + mplayer-z88dk REAL).
#
# Pipeline:
#   1. rasm assembles src/akm.z80 → build/akm.bin at ORG=$C200
#      (the akm.z80 has been edited in-place to add ORG #A000 at top).
#   2. We copy Library/MSX/mplayer-z88dk/src/akm/akm_bridge.asm into
#      build/ so its `BINARY "akm.bin"` directive finds the file in
#      its own directory.
#   3. zcc compiles main.c + 8 mplayer wrappers + the bridge into the
#      ROM. At runtime, main.c calls mplayer_engine_load() once before
#      mplayer_init() to LDIR-copy the blob from cart ROM to $A000 RAM.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
BUILD_DIR="$SCRIPT_DIR/build"
TARGET_BASE="06_sound"

ZCC="${ZCC:-/opt/z88dk/bin/zcc}"
RASM="${RASM:-$PROJECT_ROOT/Examples/ubox_example_z88dk/bin/rasm}"
UBOX_DIR="$PROJECT_ROOT/Library/MSX/ubox-msx-lib-z88dk"
UBOX_INC="$UBOX_DIR/include"
UBOX_LIB="$UBOX_DIR/lib"
MPLAYER_DIR="$PROJECT_ROOT/Library/MSX/mplayer-z88dk"
MPLAYER_INC="$MPLAYER_DIR/include"
MPLAYER_WRAPPERS="$MPLAYER_DIR/src/wrappers"
MPLAYER_BRIDGE_SRC="$MPLAYER_DIR/src/akm/akm_bridge.asm"

[[ -x "$ZCC"  ]] || { echo "Error: zcc not found at $ZCC"   >&2; exit 1; }
[[ -x "$RASM" ]] || { echo "Error: rasm not found — run: make -C $PROJECT_ROOT/Examples/ubox_example_z88dk/tools/rasm" >&2; exit 1; }
[[ -f "$UBOX_LIB/ubox.lib" ]] || { echo "ubox.lib missing — building..."; make -C "$UBOX_DIR"; }

mkdir -p "$BUILD_DIR"

# Step 1: assemble AKM player binary at ORG=$C200 (also outputs symbol file)
echo "[rasm] src/akm.z80 → build/akm.bin (ORG=\$C200)"
(cd "$SCRIPT_DIR/src" && "$RASM" akm.z80 \
    -ob "$BUILD_DIR/akm.bin" \
    -os "$BUILD_DIR/akm.sym" \
    -s -sl >/dev/null 2>&1) \
    || { echo "Error: rasm failed assembling src/akm.z80" >&2; exit 1; }
echo "  akm.bin: $(wc -c < "$BUILD_DIR/akm.bin") bytes"

# Step 2: copy bridge.asm next to akm.bin so BINARY "akm.bin" resolves
cp -f "$MPLAYER_BRIDGE_SRC" "$BUILD_DIR/akm_bridge.asm"

# Step 2.5: generate song_bindings.asm — extract _SONG (and _EFFECTS if
# present) addresses from the rasm symbol table. The C code declares
# `extern uint8_t SONG[]` which sccz80 mangles to `_SONG`; AKM's actual
# blob symbol is `SONGDISARKGENERATEEXTERNALLABEL` (Disark hint label).
extract_addr() {
    local label="$1"
    local hex_with_prefix
    hex_with_prefix="$(awk -v L="$label" '$1==L { print $2 }' "$BUILD_DIR/akm.sym")"
    # rasm prints "#A616" for hex; convert to z80asm "$A616". Empty stays empty.
    if [[ -n "$hex_with_prefix" ]]; then
        echo "${hex_with_prefix/\#/\$}"
    fi
    return 0
}
SONG_ADDR="$(extract_addr SONGDISARKGENERATEEXTERNALLABEL)" || true
EFFECTS_ADDR="$(extract_addr EFFECTSDISARKGENERATEEXTERNALLABEL)" || true
[[ -n "$SONG_ADDR" ]] || { echo "Error: SONGDISARKGENERATEEXTERNALLABEL not found in akm.sym" >&2; exit 1; }

PLY_INIT="$(extract_addr PLY_AKM_INIT)"
PLY_PLAY="$(extract_addr PLY_AKM_PLAY)"
PLY_STOP="$(extract_addr PLY_AKM_STOP)"
PLY_INITSFX="$(extract_addr PLY_AKM_INITSOUNDEFFECTS)"
PLY_ISSFXON="$(extract_addr PLY_AKM_ISSOUNDEFFECTON)"
PLY_PLAYSFX="$(extract_addr PLY_AKM_PLAYSOUNDEFFECT)"
PLY_STOPSFX="$(extract_addr PLY_AKM_STOPSOUNDEFFECTFROMCHANNEL)"
for sym in PLY_INIT PLY_PLAY PLY_STOP PLY_INITSFX PLY_ISSFXON PLY_PLAYSFX PLY_STOPSFX; do
    [[ -n "${!sym}" ]] || { echo "Error: $sym address missing in akm.sym" >&2; exit 1; }
done

{
    echo "; Auto-generated by compile.sh — z88dk-port AKM bindings"
    echo "; (extracted from build/akm.sym)"
    echo "    SECTION code_user"
    echo "    PUBLIC _SONG"
    echo "    DEFC _SONG = $SONG_ADDR"
    if [[ -n "$EFFECTS_ADDR" ]]; then
        echo "    PUBLIC _EFFECTS"
        echo "    DEFC _EFFECTS = $EFFECTS_ADDR"
    fi
    echo "    PUBLIC _PLY_AKM_INIT"
    echo "    DEFC _PLY_AKM_INIT = $PLY_INIT"
    echo "    PUBLIC _PLY_AKM_PLAY"
    echo "    DEFC _PLY_AKM_PLAY = $PLY_PLAY"
    echo "    PUBLIC _PLY_AKM_STOP"
    echo "    DEFC _PLY_AKM_STOP = $PLY_STOP"
    echo "    PUBLIC _PLY_AKM_INITSOUNDEFFECTS"
    echo "    DEFC _PLY_AKM_INITSOUNDEFFECTS = $PLY_INITSFX"
    echo "    PUBLIC _PLY_AKM_ISSOUNDEFFECTON"
    echo "    DEFC _PLY_AKM_ISSOUNDEFFECTON = $PLY_ISSFXON"
    echo "    PUBLIC _PLY_AKM_PLAYSOUNDEFFECT"
    echo "    DEFC _PLY_AKM_PLAYSOUNDEFFECT = $PLY_PLAYSFX"
    echo "    PUBLIC _PLY_AKM_STOPSOUNDEFFECTFROMCHANNEL"
    echo "    DEFC _PLY_AKM_STOPSOUNDEFFECTFROMCHANNEL = $PLY_STOPSFX"
} > "$BUILD_DIR/song_bindings.asm"
echo "  _SONG = $SONG_ADDR${EFFECTS_ADDR:+, _EFFECTS = $EFFECTS_ADDR}"
echo "  PLY_AKM_INIT=$PLY_INIT PLAY=$PLY_PLAY STOP=$PLY_STOP"
echo "  PLY_AKM_PLAYSOUNDEFFECT=$PLY_PLAYSFX ISSFXON=$PLY_ISSFXON STOPSFX=$PLY_STOPSFX"

# Step 3: compose ZCCFLAGS + SRCS and invoke zcc
ZCCFLAGS="+msx -subtype=rom -compiler=sccz80 -SO2 -create-app"
ZCCFLAGS="$ZCCFLAGS -I$UBOX_INC -I$MPLAYER_INC -I$SCRIPT_DIR/src"
ZCCFLAGS="$ZCCFLAGS -L$UBOX_LIB -lubox"

WRAPPER_SRCS=(
    "$MPLAYER_WRAPPERS/mplayer_init.asm"
    "$MPLAYER_WRAPPERS/mplayer_init_effects.asm"
    "$MPLAYER_WRAPPERS/mplayer_is_sound_effect_on.asm"
    "$MPLAYER_WRAPPERS/mplayer_play.asm"
    "$MPLAYER_WRAPPERS/mplayer_play_effect.asm"
    "$MPLAYER_WRAPPERS/mplayer_play_effect_p.asm"
    "$MPLAYER_WRAPPERS/mplayer_stop.asm"
    "$MPLAYER_WRAPPERS/mplayer_stop_effect_channel.asm"
)

case "${1:-build}" in
    build|all)
        echo "[zcc] main.c + wrappers + akm_bridge → build/$TARGET_BASE.rom"
        (cd "$SCRIPT_DIR" && "$ZCC" $ZCCFLAGS -m \
            -o "$BUILD_DIR/$TARGET_BASE" \
            src/main.c \
            "${WRAPPER_SRCS[@]}" \
            "$BUILD_DIR/akm_bridge.asm" \
            "$BUILD_DIR/song_bindings.asm")

        ROM="$BUILD_DIR/${TARGET_BASE}.rom"
        [[ -f "$ROM" ]] || { echo "Error: ROM not produced" >&2; exit 1; }
        SIZE="$(wc -c < "$ROM")"
        echo "ROM: $ROM ($SIZE bytes)"
        case "$SIZE" in
            16384|32768) echo "  -> $((SIZE / 1024)) KiB plain cartridge" ;;
            *) echo "Warning: unusual ROM size ($SIZE bytes)" >&2 ;;
        esac
        ;;
    clean) rm -rf "$BUILD_DIR"; echo "Cleaned: $BUILD_DIR" ;;
    *) echo "usage: $0 {build|clean|all}" >&2; exit 2 ;;
esac
